### ISSUE TITLE
[Android] Give ability to set type of the shared file.

### ISSUE THREAD

**Issue by Monabr** [TheArchitect123/KmpEssentials#11]
Hello.

In android code we can set 

```
type = "text/csv"
```

but for now there is no ability to do so.

**Comment by TheArchitect123** [comment]
Hi,

This can now be done using method chaining, with the function **KmpShare.setFileType(Mimes.csv)** 
You can access it via **v1.1.7**
`implementation("io.github.thearchitect123:kmpEssentials:1.1.7")`

Please review the updated documentation for more info on this. Thanks
https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/modules/shareData#share-files
