### ISSUE TITLE
[Android & iOS] [Share] Sharing the file shared without ".type" in it 

### ISSUE THREAD

**Issue by Monabr** [TheArchitect123/KmpEssentials#13]
Hello.

I have tested on iOS and Android that when I share the `file.csv` it shared like `file` but not like `file.csv`.

Please fix it.

**Comment by TheArchitect123** [comment]
Hi,

Please download **v1.1.7** and it should fix this.

`implementation("io.github.thearchitect123:kmpEssentials:1.1.7")`

I've updated the documentation for sharing Files & Text, which you can find here.
https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/modules/shareData
