### ISSUE TITLE
[Feature] [Notifications] Scheduled alarms

### ISSUE THREAD

**Issue by Monabr** [TheArchitect123/KmpEssentials#16]
Hello.

It would be nice to be able to set notification alarms like it is in Android. When you can schedule a notification for a certain time and it will be shown at the time it was scheduled.

**Comment by TheArchitect123** [comment]
This feature is done on Android side.
iOS is coming up.

**Please download the latest package (v.1.2.8), and you can find the updated documentation here.**
https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/modules/localNotifications

**Comment by TheArchitect123** [comment]
@Monabr 
This feature is now ready on iOS.
Please download the latest version v.1.5.1.

The apis are the same as android. 

In regards to your **setExact** and **set** request, there's an api available in KmpLocalNotifications ONLY for Android.
You can configure invoking setExact by calling **KmpLocalNotifications.allowSetExact(false)**, which invokes **set** only.

Default value for exact is **true**.

I'll update the documentation later.

Please note that when running repeat notifications on iOS, there's a minimum interval of 60 seconds. If you use a value less than that, it could crash. I'm thinking of invoking a custom exception handler for that so at least devs can see on the Xcode console.

**Also I'd appreciate a star and a follow on GitHub.**

**Comment by TheArchitect123** [comment]
And if you need a logging library for microsoft app insights you can check out my other library here.
https://github.com/TheArchitect123/KmpAppInsights

**Comment by TheArchitect123** [comment]
@Monabr 
I've updated the documentation.

https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/modules/localNotifications
