### ISSUE TITLE
[Send Emails] Add pre-filled data to request. 

### ISSUE THREAD

**Issue by Monabr** [TheArchitect123/KmpEssentials#17]
**Is your feature request related to a problem? Please describe.**
I want to add data to the "send email" request

**Describe the solution you'd like**
I want able to add subject and text of the email

**Describe alternatives you've considered**
In Android it could be done by `Intent.EXTRA_SUBJECT` and `Intent.EXTRA_TEXT`

**Comment by TheArchitect123** [comment]
Hi, 
This is fixed now on the latest package (v1.2.8).

**You can find the updated documentation here:**
https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/modules/localNotifications
