### ISSUE TITLE
[Google Play Rules] Give ability to include only needed part of the library in the app.

### ISSUE THREAD

**Issue by Monabr** [TheArchitect123/KmpEssentials#22]
**Is your feature request related to a problem? Please describe.**
After uploading build to the Google Play I see warning: `All developers requesting access to the photo and video permissions are required to tell Google Play about the core functionality of their app`. 
I don't use this functionality but it still included into the app and Google does not like it.

**Describe the solution you'd like**
Please give the ability to include to the app only that parts that I need.

**Comment by TheArchitect123** [comment]
@Monabr 

**Can you try again with v1.5.4?**
Tell me if it works now.

**Comment by Tommyten** [comment]
While v1.5.4 might fix the problem @Monabr is facing (haven't tested myself), it would be great if you could provide more granular modules.
For example if I want to only include Biometric Authentication I would like to be able to only include Biometric Authentication for example by having a maven artifact, that only provides the Biometric authentication. In a build.gradle it could look like this:
`implementation("io.github.thearchitect123:kmpEssentials-biometric:+")`

@Monabr if you're still facing your issue try forcefully excluding the relevant permissions like so:
```
<uses-permission
            android:name="android.permission.READ_MEDIA_IMAGES"
        tools:node="remove" />
    <uses-permission
            android:name="android.permission.READ_MEDIA_VIDEO"
        tools:node="remove" />
```
In Android Studio you can look at the Merged Manifest. By including the above code block the permissions you remove should not be in the Merged Manifest anymore.

**Comment by TheArchitect123** [comment]
@Tommyten 

I appreciate your input on this but merge manifest rules are not going to fix this issue.

@Monabr 
Please download the **latest version** (as of now it is **v1.5.7**)
And this will resolve your issue.

To replicate this problem I deployed a sample app on Google Play Internal Channel using v.1.5.4.
And I got 12 declaration requirements (including the Photos + Videos).

<img width="1445" alt="Screenshot 2024-11-16 at 1 53 23 am" src="https://github.com/user-attachments/assets/324ae97c-cd90-4e12-b735-d956b84e3bcb">


**Then when I redeployed a new version of the sample app with v1.5.7 of KmpEssentials** the declaration requirement was removed.
<img width="1447" alt="Screenshot 2024-11-16 at 1 54 35 am" src="https://github.com/user-attachments/assets/c5168c8c-dac0-46a7-9efe-1c4f9c48a6ba">
<img width="1438" alt="Screenshot 2024-11-16 at 1 56 50 am" src="https://github.com/user-attachments/assets/7c954ec0-136c-434f-8649-4d3c8c885246">

@Tommyten 
Yes, I'm planning to provide a better modularising architecture. So you developers only import the modules they need. 
It will look something like this (when you initialize the library),

Inside your shared code you would write

```
KmpEssentials.loadModules(
   useBiometric = false,
   useFilePicker = false
)
```

Default value is true (meaning all modules are loaded), and false you can configure to disable those modules from being imported.
