### ISSUE TITLE
iOS setup required for Biometric Authentication

### ISSUE THREAD

**Issue by Tiagochicoo** [TheArchitect123/KmpEssentials#3]
Hey guys, excellent work with this library!

While I was testing it out, I found that I needed to add the following to my iOS project in order to use the Biometric Authentication you describe [here](https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/modules/biometrics#any-setup-required).

I had to add this to my Info.plist inside the iOS project folder:

`<key>NSFaceIDUsageDescription</key>`
`<string>For user authentication purposes</string>`

Would be nice to add these steps for future users.

Keep up the great work!

**Comment by TheArchitect123** [comment]
Yeah sorry I forgot to add that.
Thanks for finding this.

I've pushed the changes on the site.

https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/modules/biometrics#setup-for-ios
