### ISSUE TITLE
Can you add Printing?

### ISSUE THREAD

**Issue by androidMaster378** [TheArchitect123/KmpEssentials#5]
I love this library but can you please add a printing api into it?

**Comment by TheArchitect123** [comment]
Hi thanks for the feedback.
Yes that's coming up in the next couple of versions.

I already have some new functions available for it.
After I deploy the mac apis, printing will be available too.

**Comment by TheArchitect123** [comment]
Version 1.0.0 now has printing.
Please upgrade to the latest package to get access.

You can find the documentation for it here.
https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/modules/printing/
