### ISSUE TITLE
[Docs] Missing permissions from iOS setup on Geolocation

### ISSUE THREAD

**Issue by Tiagochicoo** [TheArchitect123/KmpEssentials#6]
Hey!

For the Geolocation & Geofencing setup on iOS you're only providing the `NSLocationWhenInUseUsageDescription` key, but you need to provide two:

```
<key>NSLocationWhenInUseUsageDescription</key>
<string>Your location is needed to show nearby events.</string>

<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>Your location is needed to provide real-time updates even when the app is not active.</string>
```

https://thearchitect123.github.io/ArtifactsDocProduction/develop/kotlin/multiplatform/kmpessentials/modules/geolocation

**Comment by TheArchitect123** [comment]
Hi, Thanks for finding this.
I forgot to add the second key required for foreground services.

Refresh the page, and the key should be there.
